### ISSUE TITLE
Friction flux

### ISSUE THREAD

**Issue by brycemihal** [HydroCouple/CSHComponent#1]
Add internal shear friction flux based on Theurer et al. 1985. Jf = 9805 * Flow / Top Width * Slope.

**Comment by calebbuahin** [comment]
@brycemihal and @btneilson, I have added the friction heat flux to the code(see https://github.com/HydroCouple/CSHComponent/commit/2e064c4f484a0f9d47f2b663655fcd0318b894d3). You turn it on by setting the new flag called FLUID_FRICTION_HEAT to YES in the OPTIONS section. Please pull it, compile, and replace the CSHComponent in your existing installation. Remember to compile in release mode. Let me know if you have any trouble compiling.

**Comment by brycemihal** [comment]
Thanks Caleb for working on this. I was able to pull and compile the new
CSH component but when I turn the FLUID_FRICTION_HEAT option to YES the
model crashes. When I have it set to NO, it runs fine. I'm not comfortable
going through QT to debug the code and find the problem. Perhaps this is
something you could walk me through sometime.

The model crashes on the first CSH time step and I get the output of:

>
> [CVODE WARNING]  CVode
>   Internal t = 0 and h = 0 are such that t + h = t on the next step. The
> solver will continue anyway.
>
> [CVODE ERROR]  CVode
>   At t = 0 and h = 0, the corrector convergence test failed repeatedly or
> with |h| = hmin.
>
> CSH Solver failed
>

**Comment by calebbuahin** [comment]
@brycemihal Sorry about that. I think I forgot to initialize the friction heat variable to zero. I am going to fix it shortly and recommit it.

**Comment by calebbuahin** [comment]
I actually checked and I am initializing things correctly. Check the friction equation in element.cpp in the function `Element::computeFluidFrictionHeat()` to make sure the formulation is right.

**Comment by brycemihal** [comment]
Caleb, I did find an error in your equation: *fluidFrictionHeatFlux =
9805.0 * flow.value / (width * slope)*;. Slope should not be in the
denominator. See the attached screenshot from Theurer et al. 1985. I don't
think the formulation is throwing the error though. I looked into my
element widths in previous model runs and every element is zero for the
first time step. This would cause a NaN value when computed. It looks like
I have the initial XSECTION_AREA, WIDTH, SLOPE, FLOW, and DISPERSION_COEFF
all set to zero in my CSH .inp file. I'm guessing that if I set my WIDTH
value to something other than zero the problem will be fixed. I will test
this and let you know if it works.

[image: Screen Shot 2019-06-10 at 1.56.33 PM.png]

**Comment by calebbuahin** [comment]
@brycemihal that sounds good. Also, you can modify the code to remove my check for non zero slope since the slope is in the numerator. Please commit any changes you make. In the message just type  #1 to reference this issue.

**Comment by calebbuahin** [comment]
@brycemihal  I have actually fixed it here so nvm about committing your changes.

**Comment by brycemihal** [comment]
Caleb, I just committed my changes but under the Bryce branch. The model
appears to be working now with the change in initial width.
